### ISSUE TITLE
Refence and links feature

### ISSUE THREAD

**Issue by garvitdelhi** [mebjas/Wiki-Read-Mode#17]
By default they turn on even though user has set them to off 

@mebjas can you look at what is wrong or guide me to a fix i will fix it

**Comment by mebjas** [comment]
https://github.com/mebjas/Wiki-Read-Mode/commit/70c9187b5f8e2e39d1900bc262008d496155fc31 Seems fixed to me..
Have a look @garvitdelhi , if things go well with you too close this issue.
I'll push the code to chrome store!

**Comment by garvitdelhi** [comment]
works perfectly  now :D +1:
